---
- hosts: dal
  remote_user: ubuntu
  tasks:
  - set_fact:
      ansible_ssh_pass=your_password
  - name: "Make sure chef is installed on this server"
    become: yes
    become_user: root
    become_method: su
    action: shell dpkg -l | grep -i chef 
    register: output
  - debug: msg="{{ output.stdout }}"
  - name: "Make sure hpssacli is installed on this server"
    become: true
    action: shell dpkg -l | grep -i  hpssacli
    register: output1
  - debug: msg="{{ output1.stdout }}"
